AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an IAM role for Cloud Golden Guard audit access'

Parameters:
  TrustedAccountId:
    Type: String
    Description: 'The AWS Account ID of the trusted Cloud Golden Guard account'
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: 'Must be a valid 12-digit AWS Account ID'

Resources:
  CloudGoldenGuardAuditRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudGoldenGuardAuditRole
      Description: 'IAM role for Cloud Golden Guard to perform read-only security audits'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${TrustedAccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': 'cloud-golden-guard-audit'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
      Policies:
        - PolicyName: CloudGoldenGuardAdditionalPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: S3BucketReadAccess
                Effect: Allow
                Action:
                  - 's3:GetBucketPublicAccessBlock'
                  - 's3:GetBucketVersioning'
                  - 's3:GetBucketLogging'
                  - 's3:GetBucketEncryption'
                  - 's3:GetBucketTagging'
                  - 's3:GetBucketPolicy'
                  - 's3:GetBucketPolicyStatus'
                  - 's3:GetBucketAcl'
                  - 's3:ListBucket'
                Resource: '*'
              
              - Sid: EC2ReadAccess
                Effect: Allow
                Action:
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeInstanceAttribute'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeSecurityGroupRules'
                  - 'ec2:DescribeVolumes'
                  - 'ec2:DescribeSnapshots'
                  - 'ec2:DescribeImages'
                  - 'ec2:DescribeVpcs'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:DescribeNetworkInterfaces'
                Resource: '*'
              
              - Sid: RDSReadAccess
                Effect: Allow
                Action:
                  - 'rds:DescribeDBInstances'
                  - 'rds:DescribeDBClusters'
                  - 'rds:DescribeDBSnapshots'
                  - 'rds:DescribeDBClusterSnapshots'
                  - 'rds:ListTagsForResource'
                Resource: '*'
              
              - Sid: LambdaReadAccess
                Effect: Allow
                Action:
                  - 'lambda:GetFunction'
                  - 'lambda:GetFunctionConfiguration'
                  - 'lambda:ListFunctions'
                  - 'lambda:ListTags'
                Resource: '*'
              
              - Sid: IAMReadAccess
                Effect: Allow
                Action:
                  - 'iam:GetRole'
                  - 'iam:GetPolicy'
                  - 'iam:GetPolicyVersion'
                  - 'iam:ListAttachedRolePolicies'
                  - 'iam:ListRolePolicies'
                  - 'iam:GetRolePolicy'
                  - 'iam:ListPolicies'
                  - 'iam:ListUsers'
                  - 'iam:ListRoles'
                Resource: '*'
              
              - Sid: CloudFormationReadAccess
                Effect: Allow
                Action:
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:DescribeStackResources'
                  - 'cloudformation:ListStacks'
                Resource: '*'
      Tags:
        - Key: ManagedBy
          Value: CloudGoldenGuard
        - Key: Purpose
          Value: SecurityAudit

Outputs:
  RoleArn:
    Description: 'ARN of the created IAM role'
    Value: !GetAtt CloudGoldenGuardAuditRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
  
  RoleName:
    Description: 'Name of the created IAM role'
    Value: !Ref CloudGoldenGuardAuditRole
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'
